name: Leading a modern life while living the Gospel
author: Pascal Laliberté
url: http://by.pascallaliberte.me
lang: en
alt_lang: fr
alt_lang_url: http://par.pascallaliberte.me
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year-:month-:title/
paginate: 5
paginate_path: "page:num"
excerpt_separator: "<!-- MORE -->"
baseurl:
gems:
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - a/bower_components/jquery.smooth-scroll/index.html
